- name: Stop and Disable Apache2 service
  ansible.builtin.service:
    name: apache2
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Purge Apache2 package (including config files)
  ansible.builtin.apt:
    name: apache2*
    state: absent
    purge: yes
    autoremove: yes

- name: Remove web root and all contents
  ansible.builtin.file:
    path: "/var/www"
    state: absent
